name: sarthi
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.2  # Gemini API
  flutter_tts: ^4.0.2          # Text-to-speech
  file_picker: ^8.0.0+1        # File upload
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true